### PR TITLE
Add content, dates, and links

### LINKED ISSUE #5: Update _config.yaml to use values relevant to this workshop
Update `_config.yaml` to use values that are relevant for your workshop such as the Docker repository and tag that you will be using for the workshop. [We use jekyll variable substitution as part of this template](https://jekyllrb.com/docs/includes/#passing-parameter-variables-to-includes).

### LINKED ISSUE #6: Update the pages that will appear in the header
Update the pages that will appear in the header (`header_pages:`) in `_config.yaml`. Any page that appears in the header should have a navigation title (`nav_title:`) in its YAML header.

### LINKED ISSUE #12: Ensure that descriptions of and links to workshop content are up-to-date
Revise the course website to reflect the content this workshop will be covering. 

For virtual workshops, the areas that need to be updated are:

* The first bulletpoint in `virtual-workshop/workshop-structure.md` (which becomes `workshop/workshop-structure.md`)
* The modules we link to in `virtual-workshop/workshop-materials.md` (which becomes `workshop/workshop-materials.md`)

### PR DESCRIPTION
**Pull request by jashapiro**
This PR adds the dates for the training as well as the links that are now active. 

I also updated the workshop materials and structure pages with the topics for this workshop.

Closes #5 
Closes #6
Closes #12

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Don't we usually include the Docker repo and tag for virtual workshops?

**Comment by jashapiro** [comment]
> Don't we usually include the Docker repo and tag for virtual workshops?

We do, but we don't have those yet. (I guess the repo, but no tag yet) Those elements are not deleted, but also not updated yet.

I suppose I could say it doesn't quite close #5...

**Comment by jaclyn-taroni** [comment]
The tag follows a specific convention that you can predict though. I think your options are update those or don't close #5.

**Comment by jashapiro** [comment]
> The tag follows a specific convention that you can predict though

Such confidence in my pattern-matching!

Updated.

**Review by jaclyn-taroni — APPROVED** [review]
👍🏻  thank you!

**Pull request merged**
