### PR TITLE
Add intro to scRNA-seq slides to repo and schedule

### PR DESCRIPTION
**Pull request by allyhawkins**
Related to #7. This adds the PDF of the slides for intro to RNA-seq to the repo and the link to the slides to the schedule. I went ahead and removed any of the animated slides and hidden slides from the pdf. I also updated the links that were no longer present in the slides on google drive and they are now present in the pdf as well.

### CODE REVIEW

**Review by sjspielman — APPROVED** [review]
👍

**Comment by jashapiro** [comment]
Slide 3 link is dead: need to update to https://www.10xgenomics.com/blog/single-cell-rna-seq-an-introductory-overview-and-tools-for-getting-started

**Comment by jashapiro** [comment]
Update slide 10 link to published version?  https://doi.org/10.1093/gigascience/giac001

**Comment by allyhawkins** [comment]
Links should be updated now!

**Review by jashapiro — APPROVED** [review]
LGTM!

**Pull request merged**
